### ISSUE TITLE
Adding license in source files/Removal of copyright statements

### ISSUE THREAD

**Issue by NikolaKirev** [theappbusiness/TABResourceLoader#31]
Going through the source code, I see that a lot of the files don't have the correct license in the beginning of the file.
If nothing else, we should remove the copyright statements, since they contradict with the license.

I'm happy to do a PR with the changes.

**Comment by lucianomarisi** [comment]
Great idea, feel free to put a PR correcting the headers with the correct license.

**Comment by NikolaKirev** [comment]
Resolved by https://github.com/theappbusiness/TABResourceLoader/commit/715f124f95df07b6724f68ce2187984d2b15a32f
