### ISSUE TITLE
Type-driven development approach to get to know the types for the functions

### ISSUE THREAD

**Issue by manojmahapatra** [theappbusiness/TABResourceLoader#52]
Hi,

I was wondering, if you given a thought to introduce something like type-driven development approach which mainly focuses around types of the functions before they're implemented. 

basically i was going through this http://matt.diephouse.com/2017/05/type-driven-development-with-swift/ article and thought this could be an ideal candidate to introduce here. 

Let me know what you think. Thanks.

**Comment by lucianomarisi** [comment]
Sorry for the very late reply. The idea is great in principle as this would allows us to chain requests that are related. Aside from adding a function on the `Result` type, were you thinking about some other ideas?

**Comment by KaneCheshire** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #52: Type-driven development approach to get to know the types for the functions](https://trello.com/c/L4iHrlJ5/12-issue-52-type-driven-development-approach-to-get-to-know-the-types-for-the-functions)
