### ISSUE TITLE
NetworkServiceActivity enhancements

### ISSUE THREAD

**Issue by tbrachkov** [theappbusiness/TABResourceLoader#55]
This are just two small suggestions I have and if you think they make sense I can submit a pull request.

- The NetworkServiceActivity shared instance is better to override private init(), so it is truly unique and prevents outside objects from creating their own instances of your NetworkServiceActivity.

- Concurrent read is now provided by default on the property numberOfActiveRequests, and would be better to make it all private and add the concurrent read and the exclusive write operations to the internal queue. A way to add an exclusive write with the concurrent queue could be with a barrier flag:

> 

    public class NetworkServiceActivity {
    /// Set this property to listen to changes on the network activity status,
    /// useful for setting the isNetworkActivityIndicatorVisible on UIApplication for example
    public static var activityChangeHandler: ((_ isActive: Bool) -> Void)?
    
    static let shared = NetworkServiceActivity()
    private let queueName = "TABResourceLoader.NetworkServiceActivity.serialQueue"
    //Concurrent read, exclusive write implemented on the concurent queue with .barrier flag for the read
    private let serialQueue: DispatchQueue
    public typealias OperationBlock = () -> ()
    
    //This prevents others from using the default empty initializer for this class so it could be actulaly a real singleton
    private init() {
        self.serialQueue = DispatchQueue(label: queueName, attributes: DispatchQueue.Attributes.concurrent)
    }
    
    private(set)var numberOfActiveRequests = 0 {
        didSet {
            let hasOutstandingRequests = numberOfActiveRequests > 0
            NetworkServiceActivity.activityChangeHandler?(hasOutstandingRequests)
        }
    }
    
    /// Call this method every time a request starts
    func increaseActiveRequest() {
        self.writeExclusive { [weak self] in
            self?.numberOfActiveRequests += 1
        }
    }
    
    /// Call this method every time a request ends
    func decreaseActiveRequest() {
        self.writeExclusive { [weak self] in
            self?.numberOfActiveRequests -= 1
        }
    }
    
    /// Call this internal method to make an exclusive write to the shared object
    private func writeExclusive(_ block: @escaping OperationBlock) {
        self.serialQueue.async(flags: .barrier, execute: block)
    }
}

**Comment by lucianomarisi** [comment]
Currently we use the internal initialiser for [mocking purposes](https://github.com/theappbusiness/TABResourceLoader/blob/02159aeca6444e0c11b34bb5c4aff85dd6b194f7/Tests/TABResourceLoaderTests/Services/NetworkDataResourceServiceTests.swift#L27), so if we do remove it we'll need to find a solution for that.

Assuming I undersand correctly, the barrier approach means that we don't block while executing the `activityChangeHandler`? If so, let's go for that change.

**Comment by tbrachkov** [comment]
Oh I haven't seen this, sorry. It's not critical that the singleton has a public init just like URLSession and others. But in this design numberOfActiveRequests is not static so if by mistake someone creates a new instance of the singleton then the request count won't be correctly changed. Option to make it only singleton could be setting Other Swift Flags  for testing and checking in the implementation for the flag.
The serial DispatchQueue and the sync execution you have is enough guarantee that all the writes are done one ofter another, and since you are not actually reading this anywhere else except the tests it's ok, however if it had a public getter I would go for concurrent DispatchQueue with dispatch async barrier when writing and dispatch sync for reading back so we get a clean exclusive write and concurrent read of the numberOfActiveRequests. 
Do you think it's worth it to add the public getter function for the numberOfActiveRequests so we know it is using the very same queue for read and write?

**Comment by samdods** [comment]
The init method is internal, so it's our responsibility to ensure no more instances are created within the framework. There is no danger of accidental misuse by consumers of the framework.

**Comment by tbrachkov** [comment]
@samdods you are right completely forgot that it's a framework.

**Comment by lucianomarisi** [comment]
> Do you think it's worth it to add the public getter function for the numberOfActiveRequests so we know it is using the very same queue for read and write?

I don't think it's worth adding a public getter for `numberOfActiveRequests` as this is an internal property of the framework and not really relevant outside the framework. I do think it's worth using a concurrent queue with a barrier assuming I understood correctly how the suggested solution works. At the moment it looks like if the `activityChangeHandler` takes too long this will block network requests. If this is the case I'd say feel free to submit a PR.

**Comment by tbrachkov** [comment]
The serial queue with a sync write is enough guarantee that the writes will be thread safe. If there is no need to have any public method to get the numberOfActiveRequests, would be pointless to actually make the queue async and use barrier. I think we can close this issue. Thanks.

**Comment by lucianomarisi** [comment]
Closing as resolved.

**Comment by KaneCheshire** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #16: Consider making available as CocoaPod](https://trello.com/c/XmUdPpm5/16-issue-16-consider-making-available-as-cocoapod)
