### ISSUE TITLE
Can't encode query item that contains timezone

### ISSUE THREAD

**Issue by p-nicolaou** [theappbusiness/TABResourceLoader#89]
Hello. In one of my requests, I need to pass as a parameter a full date time including timezone +/-. My problem is that, plus symbol is not encoded into `%2B` because the system thinks is a valid character aka http://google.com/search?q=foo+bar

Is there any way, from my `Resource` to let the `NetworkDataResourceService` know that I want the plus symbol encoded?

**Comment by p-nicolaou** [comment]
Browsing through the library again, I realise that I can override `urlQueryAllowedCharacterSet` in my `Resource` class. By doing that, I am able to `.remove("+")` and the URL is getting encoded as expected.

**Comment by jonhocking** [comment]
@p-nicolaou glad you got it working :)
