### ISSUE TITLE
improvements to meet Swift API guidelines

### ISSUE THREAD

**Issue by samdods** [theappbusiness/TABResourceLoader#9]
in `NetworkResourceType` protocol, we should make the following breaking changes:

`HTTPRequestMethod` becomes `httpRequestMethod`
`HTTPHeaderFields` becomes `httpHeaderFields`
`JSONBody` becomes `jsonBody`

**Comment by samdods** [comment]
the method in the protocols `DataResourceType` and `ImageResourceType` should be:

```
func result(from: Data) -> Result<Model>
```

and the method in the protocols `JSONDictionaryResourceType` and `JSONArrayResourceType` should be:

```
func model(from: [String : Any]) -> Model?
```

**Comment by lucianomarisi** [comment]
good idea, we'll make these breaking changes for a 3.0.0 release since I don't think protocols could be deprecated
